export const rooms = [
  {
    id: 1,
    name: "Deluxe Room",
    price: 2500,
    description: "Spacious room with king-size bed",
  },
  {
    id: 2,
    name: "Suite Room",
    price: 4000,
    description: "Luxury suite with living area",
  },
  {
    id: 3,
    name: "Standard Room",
    price: 1800,
    description: "Comfortable room for short stays",
  },
  {
    id: 4,
    name: "Premium King Room",
    price: 3200,
    description: "Elegant king room with city view",
  },
  {
    id: 5,
    name: "Garden View Room",
    price: 2300,
    description: "Calm room overlooking landscaped gardens",
  },
  {
    id: 6,
    name: "Family Suite",
    price: 4600,
    description: "Spacious suite with two sleeping zones",
  },
  {
    id: 7,
    name: "Executive Room",
    price: 3500,
    description: "Modern business room with work desk",
  },
  {
    id: 8,
    name: "Club Room",
    price: 3900,
    description: "Premium room with lounge access",
  },
  {
    id: 9,
    name: "Superior Twin Room",
    price: 2400,
    description: "Twin bed setup ideal for friends or coworkers",
  },
  {
    id: 10,
    name: "Skyline Suite",
    price: 5200,
    description: "High-floor suite with panoramic skyline views",
  },
  {
    id: 11,
    name: "Courtyard Room",
    price: 2100,
    description: "Quiet room facing the inner courtyard",
  },
  {
    id: 12,
    name: "Penthouse Suite",
    price: 7800,
    description: "Top-floor luxury suite with private lounge area",
  },
  {
    id: 13,
    name: "Business Class Room",
    price: 3300,
    description: "Efficient layout with fast Wi-Fi and workspace",
  },
  {
    id: 14,
    name: "Ocean Breeze Room",
    price: 4100,
    description: "Airy room with scenic waterfront ambiance",
  },
  {
    id: 15,
    name: "Classic Queen Room",
    price: 2200,
    description: "Classic comfort with queen-size bedding",
  },
  {
    id: 16,
    name: "Urban Loft Suite",
    price: 5000,
    description: "Stylish loft-inspired suite with open layout",
  },
  {
    id: 17,
    name: "Grand Deluxe Room",
    price: 3700,
    description: "Large deluxe room with premium interiors",
  },
  {
    id: 18,
    name: "Terrace View Room",
    price: 3000,
    description: "Bright room with terrace-facing windows",
  },
  {
    id: 19,
    name: "Studio Suite",
    price: 4300,
    description: "Contemporary studio suite with lounge corner",
  },
  {
    id: 20,
    name: "Poolside Room",
    price: 3400,
    description: "Comfortable room near the pool deck",
  },
  {
    id: 21,
    name: "Heritage Room",
    price: 2800,
    description: "Traditional decor with modern comforts",
  },
  {
    id: 22,
    name: "Royal Suite",
    price: 6800,
    description: "Signature suite designed for luxury stays",
  },
  {
    id: 23,
    name: "City Lights Room",
    price: 3100,
    description: "Evening skyline views with cozy interiors",
  },
  {
    id: 24,
    name: "Comfort Twin Room",
    price: 2000,
    description: "Practical twin room for budget travelers",
  },
  {
    id: 25,
    name: "Panorama Room",
    price: 3600,
    description: "Wide-angle views from a premium corner room",
  },
  {
    id: 26,
    name: "Luxury Family Suite",
    price: 5400,
    description: "Family-focused suite with extra seating area",
  },
  {
    id: 27,
    name: "Signature King Room",
    price: 3450,
    description: "Well-appointed king room with premium bedding",
  },
  {
    id: 28,
    name: "Lake View Room",
    price: 3900,
    description: "Serene room with lake-facing windows",
  },
  {
    id: 29,
    name: "Presidential Suite",
    price: 9200,
    description: "Expansive top-tier suite with elite amenities",
  },
  {
    id: 30,
    name: "Compact Single Room",
    price: 1600,
    description: "Efficient solo room for short business trips",
  },
  {
    id: 31,
    name: "Sunrise Room",
    price: 2750,
    description: "East-facing room with beautiful morning light",
  },
  {
    id: 32,
    name: "Moonlight Suite",
    price: 4950,
    description: "Relaxing suite designed for evening comfort",
  },
  {
    id: 33,
    name: "Boutique Room",
    price: 3050,
    description: "Designer-style room with curated decor",
  },
]
